/*
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * IDConsumer.java
 * Copyright (C) 2019 University of Waikato, Hamilton, NZ
 */

package adams.gui.tools.idprovider;

import adams.core.Properties;

/**
 * Interface for components that consume IDs generated by the IDProviders.
 *
 * @author FracPete (fracpete at waikato dot ac dot nz)
 */
public interface IDConsumer {

  /**
   * Updates the model with the specified IDs.
   */
  public void setIDs(String[] ids);

  /**
   * Updates and stores the session properties on disk.
   *
   * @return		if successfully saved
   */
  public boolean updateProperties();

  /**
   * Returns the session properties.
   *
   * @return		the properties
   */
  public Properties getProperties();
}
